//------------------------------------------------------------------------------
// <auto-generated>

using UnityEngine;
using System.Collections;
using System.IO;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;

using KSP.IO;

namespace SkyTonemapper
{
	public class cameraHDR: MonoBehaviour
	{	
		Material toneMappingMaterial;
		float exposure=250;
		
		void Start()
		{	
			GetComponent<Camera> ().hdr = true;
		}

		public void settings(float inExposure)
		{
			exposure = inExposure;
		}

		public void settings(float inExposure, Material inMat)
		{
			exposure = inExposure;
			toneMappingMaterial=inMat;
		}
		

		void OnRenderImage(RenderTexture source, RenderTexture destination)
		{
			//insert bloom here

			//tone mapping: HDR -> LDR
			toneMappingMaterial.SetFloat("_ExposureAdjustment", exposure/100);
			Graphics.Blit(source, destination, toneMappingMaterial, 8); //tonemapping, 8 is choosing the photographic preset/pass
		}		
	}
}